# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      RUNNER_ALLOW_RUNASROOT : 1
    container:
      image: priyeshkpandeysf/gui-framework
      steps:
        - name: Cleaning up the $GITHUB_WORKSPACE as root from a Docker image
          run: find /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}/. -name . -o -prune -exec rm -rf -- {} + || true


    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Move into the gui-framework
        run: cd gui-framework
      - name: Run the test using the Maven
        run: mvn test -Dtest=GoogleTests#verifyGoogleWithHeadlessChromeOnDocker
