# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: browser-actions/setup-chrome@91.0.4472.77
      - run: chrome --version
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Move into the gui-framework
        run: cd clean-data-structures/gui-framework
      - name: Run the test using the Maven
        run: mvn test -Dtest=GoogleTests#verifyGoogleWithHeadlessChromeOnDocker
