# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: priyeshkpandeysf/gui-framework
      env:
        RUNNER_ALLOW_RUNASROOT: 1

    steps:
      - name: Print directory
        run: pwd
      - name: Change permissions
        run: chown -R $USER:$USER /__w/clean-data-structures/clean-data-structures
      - name: Checkout repo
        run: git clone https://github.com/priyeshkpandey/clean-data-structures.git
      - name: Move into the gui-framework
        run: cd clean-data-structures/gui-framework
      - name: Run the test using the Maven
        run: mvn test -Dtest=GoogleTests#verifyGoogleWithHeadlessChromeOnDocker
